# Generated by Django 4.2.3 on 2023-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=10),
            preserve_default=False,
        ),
    ]
