# Generated by Django 5.1.3 on 2024-11-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'can_cancel_order')]},
        ),
    ]
