# Generated by Django 4.2.6 on 2024-08-22 07:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="taggeditem",
            managers=[
                ("objetcs", django.db.models.manager.Manager()),
            ],
        ),
    ]
